import {
    Flex,
    Box,
    FormControl,
    FormLabel,
    Input,
    Checkbox,
    Stack,
    Link,
    Button,
    Heading,
    Text,
    useColorModeValue,
  } from '@chakra-ui/react';
import Head from 'next/head';
import Auth from '../components/Auth';
import Logo from '../components/Logo';
  
  export default function AuthCheck() {
    return (
        <>

        
        <Head>
<title>SIGN IN/ SIGN UP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/fiverrlogo.svg" />
</Head>
      <Flex
        minH={'100vh'}
        align={'center'}
        justify={'center'}
        bg={useColorModeValue('gray.50', 'gray.800')}>
       

        <Stack spacing={8} mx={'auto'} maxW={'lg'} py={12} px={6}>
        <Logo  />
          <Stack align={'center'}>
            <Heading fontSize={'4xl'}>Sign in to your account</Heading>
            <Text fontSize={'lg'} color={'gray.600'}>
              to enjoy all of our cool <Link color={'blue.400'}>features</Link> ✌️
            </Text>
          </Stack>
          <Box
            rounded={'lg'}
            bg={useColorModeValue('white', 'gray.700')}
            boxShadow={'lg'}
            p={19}>
                  
                <Auth  align={"center"} justify="space-between" />

          </Box>
        </Stack>
      </Flex>
      </>
    );
  }