import Head from "next/head"

const clintProject = () => {
  return (
   <>
    <Head>
        <title>StudLance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/123.svg" />
      </Head>
   </>
  )
}

export default clintProject
