import { Inter } from '@next/font/google'
import { Box, Container, Text } from '@chakra-ui/react'
import Head from 'next/head'
import GigCArd from '../components/GigCArd'
import CategoryButtons from '../components/Category'
import { useEffect, useState } from 'react'
import { collection, doc, getDoc, onSnapshot, query, where } from 'firebase/firestore'
import { db } from '../firebase'
import useAuth from '../hooks/useAuth'

const inter = Inter({ subsets: ['latin'] })

export default function Home({use}) {
  const [gigs, setGigs] = useState([]);
  const { user } = useAuth();
  const refreshData = () => {
   
    const q = query(collection(db, "Gigs"), where("user", "==", use.uid));

    onSnapshot(q, (querySnapchot) => {
      let ar = [];
      querySnapchot.docs.forEach((doc) => {
        ar.push({ id: doc.id, ...doc.data() });
      });
      setGigs(ar);
    });
    console.log(gigs)
  };

  useEffect(() => {
    refreshData();
  }, [user]);

  return (
    <>
      <Head>
        <title>Fiverr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/fiverrlogo.svg" />
      </Head>
      <Container maxW="7xl">
        <CategoryButtons />
        <Box p={4} display='flex'>
        {gigs && gigs.map((gig)=>(
        <GigCArd key={gig.id} gig={gig} />
        ))}
        </Box>
      </Container>
    </>
  )
}
