import { Inter } from '@next/font/google'
import { Container } from '@chakra-ui/react'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import GigCArd from '../components/GigCArd'
import HomeP from '../components/Home'
import CategoryButtons from '../components/Category'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
<Head>
<title>Fiverr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/fiverrlogo.svg" />
</Head>
    <Container maxW="7xl">
    
    <Navbar />
    <CategoryButtons />
    <GigCArd />
  </Container>
    </>
  )
}
